name: volunteer_connect_day4
description: "Day 4 - Production Patterns: Clean Architecture, Result pattern, Dio, Gemini AI"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  dio: ^5.7.0
  google_generative_ai: ^0.4.6
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
